# Generated by Django 6.0.4 on 2026-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_deb', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('contenue', models.TextField()),
            ],
        ),
    ]
