# Generated by Django 6.0.4 on 2026-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webradio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='contenue',
            field=models.TextField(verbose_name='Nom du programme'),
        ),
        migrations.AlterField(
            model_name='program',
            name='heure_deb',
            field=models.TimeField(verbose_name='Heure de débur'),
        ),
        migrations.AlterField(
            model_name='program',
            name='heure_fin',
            field=models.TimeField(verbose_name='Heure de fin'),
        ),
    ]
